### ISSUE TITLE
Failed to load route layer from Jun 13 or 14.

### ISSUE THREAD

**Issue by zghostz86** [waymarkedtrails/waymarked-trails-site#458]
For example: https://hiking.waymarkedtrails.org/#route?id=17692451&map=14.0/22.6254/114.403

When I click on the route position on the map, the route can still be selected and shown.
But I can't see the route layer displayed on the map. This issue happens from about 2024 Jun 13 or 14.

(failed to upload snapshot..)

**Comment by mgefst** [comment]
I am having the same issue with cycling. I cannot see anything in the route layer.

**Comment by lonvia** [comment]
Fixed.

**Comment by zghostz86** [comment]
> Fixed.

Thank you lonvia, Waymarked Trails is amazing GIS service!!!

**Comment by mgefst** [comment]
Hello!

The problem was better for me for a little while but now I am having
the exact same issue again. I have tried with multiple browsers and
even tried resetting the browsers by clearing all history and browser
data. The issue is still there.

Thank you so much in advance :)

**Comment by lonvia** [comment]
I am aware of the ongoing vandalism problems and working on mitigation. Please refrain from opening more issues.
